//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALS.PerformanceTesting.WebTest.Modules.KidsAcademy.KidsInSchools
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using TALS.PerformanceTesting.Utils.RandomDataProvider;


    [DeploymentItem("tals.performancetesting.webtests\\modules\\kidsacademy\\kidsinschools\\Data\\LoginData.csv" +
        "", "tals.performancetesting.webtests\\modules\\kidsacademy\\kidsinschools\\Data")]
    [DataSource("LoginData", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\tals.performancetesting.webtests\\modules\\kidsacademy\\kidsinschools\\Da" +
        "ta\\LoginData.csv", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "LoginData#csv")]
    [DataBinding("LoginData", "LoginData#csv", "Username", "LoginData.LoginData#csv.Username")]
    [DataBinding("LoginData", "LoginData#csv", "Password", "LoginData.LoginData#csv.Password")]
    [DeploymentItem("tals.performancetesting.webtests\\modules\\kidsacademy\\kidsinschools\\Data\\KidsInSc" +
        "hoolsData.csv", "tals.performancetesting.webtests\\modules\\kidsacademy\\kidsinschools\\Data")]
    [DataSource("UserData", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\tals.performancetesting.webtests\\modules\\kidsacademy\\kidsinschoo" +
        "ls\\Data\\KidsInSchoolsData.csv", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "KidsInSchoolsData#csv")]
    [DataBinding("UserData", "KidsInSchoolsData#csv", "Username", "UserData.KidsInSchoolsData#csv.Username")]
    [DataBinding("UserData", "KidsInSchoolsData#csv", "Email", "UserData.KidsInSchoolsData#csv.Email")]
    public class RegisterKidInSchoolCoded : WebTest
    {

        public RegisterKidInSchoolCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public void GenerateKidInSchoolData(out string parentFirstName, out string parentLastName, out string parentEmail, out string parentMobilePhone)
        {
            var parentFirstNameLength = int.Parse(RandomStringProvider.GetRandomInt(5, 14));
            parentFirstName = RandomStringProvider.GetRandomBulgarianString(parentFirstNameLength);

            var parentLastNameLength = int.Parse(RandomStringProvider.GetRandomInt(5, 14));
            parentLastName = RandomStringProvider.GetRandomBulgarianString(parentLastNameLength);

            parentEmail = RandomStringProvider.GetRandomEmail();

            parentMobilePhone = RandomStringProvider.GetRandomPhoneNumber();
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://test.telerikacademy.com/");
            request1.ThinkTime = 1;
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://test.telerikacademy.com/Users/Auth/Login");
            request2.ThinkTime = 9;
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/"));
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://test.telerikacademy.com/Users/Auth/Login");
            request3.ThinkTime = 1;
            request3.Method = "POST";
            request3.ExpectedResponseUrl = "http://test.telerikacademy.com/";
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/Users/Auth/Login"));
            FormPostHttpBody request3Body = new FormPostHttpBody();
            request3Body.FormPostParameters.Add("UsernameOrEmail", this.Context["LoginData.LoginData#csv.Username"].ToString());
            request3Body.FormPostParameters.Add("Password", this.Context["LoginData.LoginData#csv.Password"].ToString());
            request3.Body = request3Body;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://test.telerikacademy.com/Administration/Navigation");
            request4.ThinkTime = 2;
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/"));
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools");
            request5.ThinkTime = 1;
            request5.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/Administration/Navigation"));
            WebTestRequest request5Dependent1 = new WebTestRequest("http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools/Users" +
                    "InKidsSchoolsRead");
            request5Dependent1.ThinkTime = 5;
            request5Dependent1.Method = "POST";
            request5Dependent1.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request5Dependent1.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request5Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools"));
            FormPostHttpBody request5Dependent1Body = new FormPostHttpBody();
            request5Dependent1Body.FormPostParameters.Add("sort", "UserId-desc");
            request5Dependent1Body.FormPostParameters.Add("page", "1");
            request5Dependent1Body.FormPostParameters.Add("pageSize", "25");
            request5Dependent1Body.FormPostParameters.Add("group", "");
            request5Dependent1Body.FormPostParameters.Add("filter", "");
            request5Dependent1.Body = request5Dependent1Body;
            request5.DependentRequests.Add(request5Dependent1);
            yield return request5;
            request5 = null;

            string parentFirstName, parentLastName, parentEmail, parentPhone;
            GenerateKidInSchoolData(out parentFirstName, out parentLastName, out parentEmail, out parentPhone);

            WebTestRequest request6 = new WebTestRequest("http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools/UserI" +
                    "nKidsSchoolCreate");
            request6.ThinkTime = 4;
            request6.Method = "POST";
            request6.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools"));
            FormPostHttpBody request6Body = new FormPostHttpBody();
            request6Body.FormPostParameters.Add("sort", "");
            request6Body.FormPostParameters.Add("group", "");
            request6Body.FormPostParameters.Add("filter", "");
            request6Body.FormPostParameters.Add("UserInKidsSchoolId", "0");
            request6Body.FormPostParameters.Add("KidsSchoolId", "8");
            request6Body.FormPostParameters.Add("StatusInKidsSchool", "false");
            request6Body.FormPostParameters.Add("UserId", "0");
            request6Body.FormPostParameters.Add("AcademyNumber", "");
            request6Body.FormPostParameters.Add("Username", this.Context["UserData.KidsInSchoolsData#csv.Username"].ToString());
            request6Body.FormPostParameters.Add("Email", this.Context["UserData.KidsInSchoolsData#csv.Email"].ToString());
            request6Body.FormPostParameters.Add("FirstName", "");
            request6Body.FormPostParameters.Add("LastName", "");
            request6Body.FormPostParameters.Add("About", "");
            request6Body.FormPostParameters.Add("SchoolName", "");
            request6Body.FormPostParameters.Add("Name", "");
            request6Body.FormPostParameters.Add("WorkEducationStatusName", "");
            request6Body.FormPostParameters.Add("Phone", "");
            request6Body.FormPostParameters.Add("CityId", "0");
            request6Body.FormPostParameters.Add("CityName", "");
            request6Body.FormPostParameters.Add("Website", "");
            request6Body.FormPostParameters.Add("SkypeUsername", "");
            request6Body.FormPostParameters.Add("FacebookUrl", "");
            request6Body.FormPostParameters.Add("GooglePlusUrl", "");
            request6Body.FormPostParameters.Add("LinkedInUrl", "");
            request6Body.FormPostParameters.Add("TwiterUrl", "");
            request6Body.FormPostParameters.Add("ParentFirstName", parentFirstName);
            request6Body.FormPostParameters.Add("ParentLastName", parentLastName);
            request6Body.FormPostParameters.Add("ParentFullName", "");
            request6Body.FormPostParameters.Add("ParentEmail", parentEmail);
            request6Body.FormPostParameters.Add("ParentPhone", parentPhone);
            request6Body.FormPostParameters.Add("ProfileAvatarImagePath", "");
            request6.Body = request6Body;
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools");
            request7.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/Administration/Navigation"));
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools/Users" +
                    "InKidsSchoolsRead");
            request8.ThinkTime = 4;
            request8.Method = "POST";
            request8.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request8.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request8.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools"));
            FormPostHttpBody request8Body = new FormPostHttpBody();
            request8Body.FormPostParameters.Add("sort", "UserId-desc");
            request8Body.FormPostParameters.Add("page", "1");
            request8Body.FormPostParameters.Add("pageSize", "25");
            request8Body.FormPostParameters.Add("group", "");
            request8Body.FormPostParameters.Add("filter", "");
            request8.Body = request8Body;
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://test.telerikacademy.com/KidsAcademy/TeacherAdministrationUsersInKidsSchool" +
                    "/UserInKidsSchoolDestroy");
            request9.ThinkTime = 5;
            request9.Method = "POST";
            request9.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request9.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request9.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools"));
            FormPostHttpBody request9Body = new FormPostHttpBody();
            request9Body.FormPostParameters.Add("KidsSchoolId", "0");
            request9Body.FormPostParameters.Add("StatusInKidsSchool", "true");
            request9Body.FormPostParameters.Add("Username", this.Context["UserData.KidsInSchoolsData#csv.Username"].ToString());
            request9Body.FormPostParameters.Add("Email", this.Context["UserData.KidsInSchoolsData#csv.Email"].ToString());
            request9Body.FormPostParameters.Add("ParentFullName", string.Concat(parentFirstName," ",parentLastName));
            request9Body.FormPostParameters.Add("ParentEmail", parentEmail);
            request9Body.FormPostParameters.Add("ParentPhone", parentPhone);
            request9Body.FormPostParameters.Add("ProfileAvatarImagePath", "/Content/Images/DefaultAvatar/default_180x180.jpg");
            request9.Body = request9Body;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://test.telerikacademy.com/Users/Auth/LogOut");
            request10.ThinkTime = 1;
            request10.ExpectedResponseUrl = "http://test.telerikacademy.com/";
            request10.Headers.Add(new WebTestRequestHeader("Referer", "http://test.telerikacademy.com/KidsAcademy/AdministrationUsersInKidsSchools"));
            yield return request10;
            request10 = null;
        }
    }
}
